Test on Plone 5.1.6.
With Plone 5.0.10 the tests pass, except for `browser.txt`.
This fails due to a security check in getToolByName,
which fails on the FauxArchetypeTool in the portal factory.
The check in Products/CMFPlone/earlypatches/security.py knows about this fake tool,
but it goes wrong anyway.
Seems ignorable, and in Plone 5.1 it is fine.
5.0 is out of support anyway.

```
$ bin/test -t browser.txt
collective.recaptcha is unavailable: captcha tests will be skipped.
collective.funkload is unavailable. Ignoring load tests.
Running Products.PloneFormGen.tests.pfgtc.Products.PloneFormGen:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.143 seconds.
  Set up plone.app.testing.layers.PloneFixture in 5.523 seconds.
  Set up plone.app.testing.bbb.PloneTestCaseFixture in 0.830 seconds.
  Set up Products.PloneFormGen.tests.pfgtc.Fixture in 0.315 seconds.
  Set up plone.testing.z2.ZServer in 0.506 seconds.
  Set up Products.PloneFormGen.tests.pfgtc.Products.PloneFormGen:Functional in 0.000 seconds.
  Running:
    1/1 (100.0%)

Failure in test /Users/maurits/community/Products.PloneFormGen/Products/PloneFormGen/tests/browser.txt
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2224, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for browser.txt
  File "/Users/maurits/community/Products.PloneFormGen/Products/PloneFormGen/tests/browser.txt", line 0

----------------------------------------------------------------------
File "/Users/maurits/community/Products.PloneFormGen/Products/PloneFormGen/tests/browser.txt", line 37, in browser.txt
Failed example:
    browser.getLink('Form Folder').click()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest browser.txt[23]>", line 1, in <module>
        browser.getLink('Form Folder').click()
      File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py", line 445, in click
        self.browser.mech_browser.follow_link(self.mech_link)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 569, in follow_link
        return self.open(self.click_link(link, **kwds))
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 203, in open
        return self._mech_open(url, data, timeout=timeout)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 230, in _mech_open
        response = UserAgentBase.open(self, request, data)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_opener.py", line 204, in open
        response = meth(req, response)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_urllib2_fork.py", line 457, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_opener.py", line 221, in error
        result = apply(self._call_chain, args)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_urllib2_fork.py", line 332, in _call_chain
        result = func(*args)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_urllib2_fork.py", line 571, in http_error_302
        return self.parent.open(new)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 203, in open
        return self._mech_open(url, data, timeout=timeout)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 230, in _mech_open
        response = UserAgentBase.open(self, request, data)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_opener.py", line 193, in open
        response = urlopen(self, req, data)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_urllib2_fork.py", line 344, in _open
        '_open', req)
      File "/Users/maurits/shared-eggs/cp27m/mechanize-0.2.5-py2.7.egg/mechanize/_urllib2_fork.py", line 332, in _call_chain
        result = func(*args)
      File "/Users/maurits/shared-eggs/cp27m/plone.testing-4.1.3-py2.7.egg/plone/testing/_z2_testbrowser.py", line 82, in http_open
        return self.do_open(connectionFactory, req)
      File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1195, in do_open
        h.request(req.get_method(), req.get_selector(), req.data, headers)
      File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/testing.py", line 76, in request
        self.response = self.caller(request_string, handle_errors)
      File "/Users/maurits/shared-eggs/cp27m/plone.testing-4.1.3-py2.7.egg/plone/testing/_z2_testbrowser.py", line 144, in wrapped_func
        return func(*args, **kw)
      File "/Users/maurits/shared-eggs/cp27m/plone.testing-4.1.3-py2.7.egg/plone/testing/_z2_testbrowser.py", line 246, in __call__
        debug=not handle_errors,
      File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.27-py2.7.egg/ZPublisher/Test.py", line 202, in publish_module
        response = publish(request, module_name, after_list, debug=debug)
      File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.27-py2.7.egg/ZPublisher/Publish.py", line 138, in publish
        request, bind=1)
      File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.27-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
        if debug is not None: return debug(object,args,context)
      File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.27-py2.7.egg/ZPublisher/Publish.py", line 48, in call_object
        result=apply(object,args) # Type s<cr> to step into published object.
      File "/Users/maurits/shared-eggs/cp27m/Products.ATContentTypes-2.2.14-py2.7.egg/Products/ATContentTypes/tool/factory.py", line 473, in __call__
        temp_obj = tempFolder.__getitem__(id)
      File "/Users/maurits/shared-eggs/cp27m/Products.ATContentTypes-2.2.14-py2.7.egg/Products/ATContentTypes/tool/factory.py", line 222, in __getitem__
        _createObjectByType(type_name, self, id)
      File "/Users/maurits/shared-eggs/cp27m/Products.ATContentTypes-2.2.14-py2.7.egg/Products/ATContentTypes/tool/factory.py", line 77, in _createObjectByType
        return fti._constructInstance(container, id, *args, **kw)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 552, in _constructInstance
        newid = m(id, *args, **kw)
      File "<string>", line 7, in addFormFolder
      File "/Users/maurits/community/Products.PloneFormGen/Products/PloneFormGen/content/form.py", line 846, in initializeArchetype
        self.invokeFactory('FormMailerAdapter', 'mailer')
      File "/Users/maurits/shared-eggs/cp27m/Products.ATContentTypes-2.2.14-py2.7.egg/Products/ATContentTypes/lib/constraintypes.py", line 289, in invokeFactory
        RESPONSE=None, *args, **kw)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
        return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
        ob = info.constructInstance(container, id, *args, **kw)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
        return self._constructInstance(container, id, *args, **kw)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 559, in _constructInstance
        notify(ObjectAddedEvent(obj, container, newid))
      File "/Users/maurits/shared-eggs/cp27m/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
        subscriber(event)
      File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
        zope.component.subscribers(event, None)
      File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
        return sitemanager.subscribers(objects, interface)
      File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
        return self.adapters.subscribers(objects, provided)
      File "/Users/maurits/shared-eggs/cp27m/zope.interface-3.6.7-py2.7-macosx-10.14-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
        subscription(*objects)
      File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
        zope.component.subscribers((event.object, event), None)
      File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
        return sitemanager.subscribers(objects, interface)
      File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
        return self.adapters.subscribers(objects, provided)
      File "/Users/maurits/shared-eggs/cp27m/zope.interface-3.6.7-py2.7-macosx-10.14-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
        subscription(*objects)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/CMFCatalogAware.py", line 262, in handleContentishEvent
        ob.notifyWorkflowCreated()
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/CMFCatalogAware.py", line 188, in notifyWorkflowCreated
        wftool.notifyCreated(self)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/WorkflowTool.py", line 289, in notifyCreated
        self._reindexWorkflowVariables(ob)
      File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/WorkflowTool.py", line 635, in _reindexWorkflowVariables
        ob.reindexObject(idxs=vars)
      File "/Users/maurits/shared-eggs/cp27m/Products.Archetypes-1.10.19-py2.7.egg/Products/Archetypes/CatalogMultiplex.py", line 108, in reindexObject
        catalogs = self.getCatalogs()
      File "/Users/maurits/shared-eggs/cp27m/Products.Archetypes-1.10.19-py2.7.egg/Products/Archetypes/CatalogMultiplex.py", line 23, in getCatalogs
        at = getToolByName(self, TOOL_NAME, None)
      File "<string>", line 17, in check_getToolByName
    TypeError: Object found is not a portal tool (archetype_tool)

  Ran 1 tests with 1 failures and 0 errors in 1.955 seconds.
Tearing down left over layers:
  Tear down Products.PloneFormGen.tests.pfgtc.Products.PloneFormGen:Functional in 0.000 seconds.
  Tear down plone.testing.z2.ZServer in 2.844 seconds.
  Tear down Products.PloneFormGen.tests.pfgtc.Fixture in 0.003 seconds.
  Tear down plone.app.testing.bbb.PloneTestCaseFixture in 0.009 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.062 seconds.
  Tear down plone.testing.z2.Startup in 0.004 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.001 seconds.
```