Fixed propertiestool.xml to not break importing types_not_searched.
The property does not exist anymore in latest Plone 5, so it needs a
types definition, otherwise GenericSetup quits with an error:

  Module Products.GenericSetup.utils, line 735, in _initProperties
  ValueError: undefined property 'types_not_searched'